<?php

class Resources {

    private $allowed = [
        'automatic_alerts',
        'alerts',
        'alert_types',
        'additional_objects',
        'agri_work_plan',
        'agri_work_plan_application_mix_items',
        'agronomist_assignments',
        'agronomist_fields',
        'agro_operations',
        'application_mix_items',
        'chemicals',
        'company',
        'counterparties',
        'crops',
        'data_source_gps_loggers',
        'equipment_assignments',
        'fertilizers',
        'field_group',
        'field_scout_report_threat_mapping_item',
        'field_scout_report',
        'scout_report_point',
        'scout_report_point_issue',
        'scout_report_point_issue_plant_part',
        'scout_report_point_measurement',
        'field_shapes',
        'field_shape_land_parcel_mapping_items',
        'fields',
        'fuel_movements',
        'gps_loggers',
        'gps_logger_mapping_items',
        'group_folders',
        'harvest_weighings',
        'historical_values',
        'history_items',
        'implement',
        'implement_region_mapping_items',
        'inventory_history_items',
        'land_documents',
        'land_parcels',
        'land_document_land_parcel_mapping_item',
        'machine_regions',
        'machine_region_mapping_items',
        'machine_groups',
        'machine_task_agro_operation_mapping_item',
        'machine_task_field_mapping_item',
        'machine_task',
        'machine',
        'maintenance_type',
        'maintenance_type_group',
        'maintenance_record',
        'maintenance_record_row',
        'maintenance_record_row_spare_part_mapping_item',
        'maintenance_plan',
        'maintenance_plan_row',
        'maintenance_plan_row_spare_part_mapping_item',
        'notes',
        'odometer_states',
        'personal_identifiers',
        'plant_threat',
        'plant_threat_item',
        'plant_threat_item_field_mapping_item',
        'photo',
        'productivity_estimate',
        'productivity_estimate_history',
        'satellite_images',
        'scouting_tasks',
        'scouting_task_points',
        'seed',
        'soil_test',
        'soil_test_sample',
        'spare_part',
        'spare_part_manufacturer',
        'user',
        'user_role',
        'user_role_assignments',
        'user_role_permissions',
        'version',
        'weather_history_items',
        'work_record',
        'work_record_machine_region_mapping_item',
        'work_type',
        'work_type_group',
    ];

    private function decamelize($string){
        return strtolower(preg_replace(['/([a-z\d])([A-Z])/', '/([^_])([A-Z][a-z])/'], '$1_$2', $string));
    }

    public function check($resource){
        return in_array($this->decamelize($resource), $this->allowed);
    }

}
